### ISSUE TITLE
OPC Template Override Integration

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template#54]
When it comes to e-commerce and converting visiter's to shoppers, it is essential to provide and easy way to checkout. With that said, I have decided to add the necessary template override files for the awesome One-Page Checkout plugin by @lat9. 

You can download OPC on Github:
https://github.com/lat9/one_page_checkout

or via the Zen-Cart plugin section:
https://www.zen-cart.com/downloads.php?do=file&id=2095

Any objections? too bad....

**Comment by lat9** [comment]
Thanks for the mention, @zcadditions!
