### ISSUE TITLE
Integrate ImageHandler in additional image modal

### ISSUE THREAD

**Issue by Zen4All** [zcadditions/ZCA-Bootstrap-Template#55]
Great template, and a nice base to use, but when using with Image Handler 5, the additional image slider (in the modal) does not make use of Image Handler.
I reworked some files to make Image Handler work in the modal, but it may be nice to mention this in the readme, for the templamplate, and/or Image Handler.

@lat9  I reference you here, as you are the current maintainer of IH 😉

**Comment by lat9** [comment]
Thanks, @Zen4All, I'll track this here and update the IH readme to note the pre-integration with this template!

**Comment by zcadditions** [comment]
@Zen4All  can you post the changes you made to incorporate Image Handler.

**Comment by Zen4All** [comment]
Will do that tomorrow

**Comment by zcadditions** [comment]
I don't use IH, if someone wants to help out with this, I will leave open but not for long.

**Comment by Zen4All** [comment]
see #59
