### ISSUE TITLE
Width of input fields too wide on wider screens

### ISSUE THREAD

**Issue by drbyte** [zcadditions/ZCA-Bootstrap-Template#57]
With this template the default display-width of input fields is now full-column, instead of the defaults provided by core ZC.

Thus, data-entry fields for customer-registration/login, attribute-selection/typing, and especially credit-card data values, is exceptionally wide when viewed on wide-screens.

<img width="2554" alt="screen shot 2018-05-02 at 11 55 26 am" src="https://user-images.githubusercontent.com/404472/39534744-4cd124ee-4e00-11e8-876f-2f2a35ae6b18.png">

**Comment by Zen4All** [comment]
In the zc1.5.6 admin side i used a div with class="col-md-6 col-lg-9"

**Comment by drbyte** [comment]
I don't have a firm position on it, but some ideas come to mind:

- maybe the template shouldn't be full-width after a certain size?  Does `container` vs `container-fluid` offer this?
- could add a new `row` into the inner segments that uses `justify-content-center`, and then set the inner cards/sections to narrower columns

Example, on the payment-options page I've toyed with using this slight HTML adjustment, to get the following layout (note I've turned the left/right columns back on, even during checkout, cuz full-screen-width is painfully odd-looking). 

<img width="790" alt="screen shot 2018-05-03 at 2 35 13 pm" src="https://user-images.githubusercontent.com/404472/39596128-7490614a-4edf-11e8-9361-6d5938ecabcf.png">
<img width="1025" alt="screen shot 2018-05-03 at 2 34 03 pm" src="https://user-images.githubusercontent.com/404472/39596137-784503f4-4edf-11e8-903e-5f98c994f760.png">

ALSO note: the code above shows both `col-sm-7 col-md-7` which is somewhat redundant (I was experimenting). 
If I change it from 7 to a value below 6, then the "cards" for "payment modules" wrap into 2 columns, 1-per-row, like below. I think it'd be great to let them wrap, but allow multiple-stacking per column instead of just 1-per-row.  ie: in the following image the check/moneyorder floats on its own below, instead of sitting in the 2nd column where there's plenty of space for it. 
Here's what changing 7 to 5 looks like:
<img width="1032" alt="screen shot 2018-05-03 at 2 40 29 pm" src="https://user-images.githubusercontent.com/404472/39596340-0211bdfc-4ee0-11e8-8574-c1e036aa3a6e.png">

**Comment by zcadditions** [comment]
> I think it'd be great to let them wrap, but allow multiple-stacking per column instead of just 1-per-row. ie: in the following image the check/moneyorder floats on its own below, instead of sitting in the 2nd column where there's plenty of space for it.

This is easily doable, kinda duplicates the layout of OPC.

I have this done on the demo
http://www.zcadditions.com/bootstrap_tpl_demo/

This was accomplished by adding a wrapping div in the 3 tpl checkout files using BS card columns
https://getbootstrap.com/docs/4.0/components/card/#card-columns

I also added some CSS for ability to alter column count for device sizes
```
/* Small devices (landscape phones, 576px and up) */
@media (min-width: 576px) { 
.card-columns {
  -webkit-column-count: 1;
  -moz-column-count: 1;
  column-count: 1;
}   
}

/*  Medium devices (tablets, 768px and up) */
@media (min-width: 768px) {
.card-columns {
  -webkit-column-count: 1;
  -moz-column-count: 1;
  column-count: 1;
}  
}

/* Large devices (desktops, 992px and up) */
@media (min-width: 992px) {
.card-columns {
  -webkit-column-count: 2;
  -moz-column-count: 2;
  column-count: 2;
}  
}
```

**Comment by zcadditions** [comment]
I am about to open B&M business, if this is something that would work for vast majority I'll update Git as time permits
