### ISSUE TITLE
Responsive Carousel Banner

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template#63]
I think this template should include a home page carousel banner, BS has this function and is the way I am leaning.

Any suggestions for a good carousel banner? or should this be left as a plugin?

**Comment by lat9** [comment]
It's only just been posted to the Zen Cart plugins, but how about the _**ZC Home Page Carousel**_ (https://www.zen-cart.com/downloads.php?do=file&id=2208)?

**Comment by zcadditions** [comment]
Not a products carousel. A banner carousel :-)

https://getbootstrap.com/docs/4.1/components/carousel/
