### ISSUE TITLE
Image Light-box vs. existing Modal 

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template#64]
I am thinking of adding a BS light-box as an option to the existing modal.

Any suggestions on a good light-box? or should this be left as a Modal? or should this be left as a plugin?

**Comment by drbyte** [comment]
I'd make it an included plugin.
That way it'll make it easier for people to see how to substitute their own, reducing support requests ;)

The modal is "okay". However, a good swipe-friendly lightbox would be quite practical from a mobile-perspective. I like photoswipe which I mentioned in https://github.com/zencart/zencart/issues/299

Another common commercial plugin I see installed is https://www.magictoolbox.com/zen-cart/ ... granted, its integration is currently hard-coded to default ZC distribution.

**Comment by zcadditions** [comment]
Okay, seeing how no other input was given I went with PhotoSwipe
http://photoswipe.com/

I have this completed, you can see in action here:
http://www.zcadditions.com/bootstrap_tpl_demo/index.php?main_page=product_info&cPath=22&products_id=34

I will try to update git by the weekend
