### ISSUE TITLE
Missing css file

### ISSUE THREAD

**Issue by Zen4All** [zcadditions/ZCA-Bootstrap-Template#67]
The css file called on this line is missing from the package
https://github.com/zcadditions/ZCA-Bootstrap-Template/blob/748e39136eec60e338323b41c437fa17e5df976c/YOUR_ADMIN/zca_bootstrap_colors.php#L71

**Comment by zcadditions** [comment]
Not missing, decided not to add custom style to the admin page, simply didn't remove the call to. So it can be removed.

I'll update git and submit to zen, looks like new version never got updated anyways...

**Comment by Zen4All** [comment]
Better wait a little. I have some more changes for this file. I'll make a or tomorrow.

**Comment by Zen4All** [comment]
see: #68
