### ISSUE TITLE
Feature Request: Color picker changes

### ISSUE THREAD

**Issue by Zen4All** [zcadditions/ZCA-Bootstrap-Template#69]
I like the color picker. This makes it easier for (non tech savvy ) people to make basic changes.

As a feature request I would like to see the database values be moved to a separate table.
- This makes maintainability easier when upgrading ZC.
- Also will it allow for additional parameters, like adding the template name. This way you can edit  other templates ( a bit like the side-box controller page)

If interested, I can make a pr for this, or maybe we should split the color picker to a new module.

**Comment by zcadditions** [comment]
I agree with a separate table. Was originally going to go that route....

I am also okay with additional parameters but I think a check will need to be implemented to see if it is the bootstrap template or a clone of.

I am personally not interested in splitting the color picker to a new module. The actual stylesheet_zca_colors.php file will have no effect on (some elements) of non bootstrap templates. 

I believe @dbltoe has plans to update the [Responsive Color Changes for 155](https://www.zen-cart.com/downloads.php?do=file&id=2088) with admin controls.

**Comment by Zen4All** [comment]
I understand your reasoning about not splitting of, as your right about non-existing parameters.

I'll contact @dbltoe to learn about his plans.

**Comment by zcadditions** [comment]
I just have a feeling it would be extremely confusing if I release a separate module for non bootstrap templates and @dbltoe does as well. 

I don't think it would be hard to call a separate colors.php file based on template though.

I'll have to think on this one before I rule it completely out.

**Comment by drbyte** [comment]
I'd love to see a collaboration on building a color-picker for ZC core code, such that it could work harmoniously with both this Bootstrap template and @dbltoe 's template-enhancer.
Thus, much of this effort could be shared across multiple purposes so everyone benefits.

**Comment by zcadditions** [comment]
I don't mind collaboration. As long as the collaborators understand upfront my primary business takes precedence and my time is very limited.

**Comment by dbltoe** [comment]
I am more than happy to add whatever I can to this project.  My whole goal was to make color selection easier for the general Zen Cart store owner.  I felt that Anne went one step too far in combining a lot of stylesheet calls based simply on the color used.  My goal, and that of @haredo who assisted, was to allow the stylesheet to be sorted by section versus color.  Then, changing an H2 in the left column would not change a font color in a search block.
My dream of simply having the user place hex, rgb, or rgba code in an admin menu is not going to happen any time soon if left up to me or @haredo.  My programming background with ColdFusion is often more of a hindrance than a help.  Like most, however, I know what I want.  It's just the getting there.;-)
I've spent little time with the bootstrap template and am not committed to either template other than that the stylesheet should be sorted in such a manner as to result in selecting as few as three colors to have the site "sales ready".  That's what we tried to accomplish with the color change mod.
As I mentioned with Erik in a PM, the wife is getting a new knee in August which will keep us closer to home for a while.  Questions or comments can be addressed to my moniker at gmail.

**Comment by Zen4All** [comment]
I have created a new repo, and will add you guys to the team. You do not have to participate, but it will keep you informed of what is going on.
This will also be the place to discuss what is needed in the "stand alone" Color Picker, before we start coding.

**Comment by zcadditions** [comment]
moved to:

https://github.com/zcadditions/ZCA-Template-Color-Picker
