### ISSUE TITLE
tpl_modules_attributes.php, missing 'optionName' class

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template#71]
Various option-handling plugins (such as Products' Options' Stock and Numinix Products Variants) expect that an option's name is present by searching for elements with a class of `optionName`.  This class is currently missing from the template's attributes-formatting module.

**Comment by lat9** [comment]
Available for your review, @zcadditions.

**Comment by zcadditions** [comment]
Thanks @lat9
