### ISSUE TITLE
missing $define_page for products_all, featured_products & products_new

### ISSUE THREAD

**Issue by Zen4All** [zcadditions/ZCA-Bootstrap-Template#76]
Zen Cart is complaining about the missing define for FILENAME_DEFINE_PRODUCTS_ALL, FILENAME_DEFINE_FEATURED_PRODUCTS, FILENAME_DEFINE_PRODUCTS_NEW.

**Comment by zcadditions** [comment]
Think the code to include a define page got carried over, I was working on a project to include define pages on every page. LOL
